version: "3.7"

services:
  upwork.user.project.task:
    build:
      context: .
      target: development
    env_file:
    - .env
    environment:
    - POSTGRES_HOST=postgres
    entrypoint:
    - ./wait-for
    - postgres:5432
    - --
    - yarn
    - start
    depends_on:
    - postgres
    volumes:
    - /opt/app/node_modules
    - .:/opt/app
  postgres:
    image: postgres:alpine
    environment:
    - POSTGRES_USER=${POSTGRES_USERNAME:-root}
    - POSTGRES_DB=${POSTGRES_DATABASE:-database}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-null}
